import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-black text-white">
        <main>{children}</main>
      </body>
    </html>
  );
}
