name: Django CI

on:
  push:
    branches: [ "dev", "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]  # Test against Python 3.9 and 3.10

    steps:
    - uses: actions/checkout@v2  # Use the v2 version of checkout
    - name: Set up Python
      uses: actions/setup-python@v2  # Use the v2 version of setup-python
      with:
        python-version: ${{ matrix.python-version }}  # Use the Python version from the matrix
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies if requirements.txt exists
    - name: Run Tests
      run: |
        python manage.py test

# name: Django CI

# on:
#   push:
#     branches: [ "dev", "*" ]
#   pull_request:
#     branches: [ "*" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.12]

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.x"
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#     # - name: Run Tests
#     #   run: |
#     #     python manage.py test
