name: Django CI

on:
  push:
    branches: [ "dev", "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install Dependencies
      run: |
        python -m pipenv install --upgrade pipenv
        pipenv install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
