name: Django CI

on:
  push:
    branches: [ "*" ] # Run on any push event from any branch
  pull_request:
    branches: [ "*" ] # Run on pull requests from any branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0] # Use the latest version of Python

    steps:
    - uses: actions/checkout@v4 # Update to checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Update to setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py test
