name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, "latest"] # Update to the latest stable version of Node.js

    steps:
    - uses: actions/checkout@v4 # Update to the latest version of checkout action
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 # Update to the latest version of setup-node action
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
          
